### ISSUE TITLE
C# 6 support ?

### ISSUE THREAD

**Issue by gwenzek** [OmniSharp/omnisharp-sublime#217]
Hi,

I was wondering if there is a way to handle C# 6 with Omnisharp.
Is it already implemented, work in progress, planned ... ?

I looked in the docs and on Google but I didn't find anything.

**Comment by samiraguiar** [comment]
Found it. You can set the path to MSBuild adding the following line to the `config.json` file:
`"MSBuildPath" : "C:/Progra~2/MSBuild/14.0/Bin/",`

This was taken from [here](https://sreal.github.io/jekyll/2016/01/27/omnisharp-and-c-6.html).

To find the config file location, go to Preferences > Package Settings > OmniSharp > Settings - User. There should be a `omnisharp_server_config_location` entry with the file you need to edit.

**Comment by DH3650** [comment]
If I have this code:
``` csharp
string name = "OmniSharp";
Console.WriteLine($"Name = {name}");
```

the `omnisharp_onsave_codecheck` returns
`Error : Unexpected character $`

The method from [here](https://sreal.github.io/jekyll/2016/01/27/omnisharp-and-c-6.html) doesn't work to this problem :(

**Comment by wojoeraf** [comment]
Unfortunately the described method (`"MSBuildPath" : "C:/Progra~2/MSBuild/14.0/Bin/"`, to config.json) doesn't work for me either.

Someone who can help on this?

I'm a bit upset that the praised omnisharp ("So there you have it, C# as a first class citizen in Sublime Text", see [here](http://blog.jonathanchannon.com/2014/11/12/csharp-first-class-citizen-sublime-text/)) has no real support for C# 6 and the help for this issue remains silent so far.

Any help appreciated, otherwise I wasted my time on trying to get sublime working with C#.

Thanks a lot.

**Comment by Xirui** [comment]
Same issue with me. Workaround with config.json did not work.

Could you kindly help @jchannon ?

**Comment by jchannon** [comment]
I'm no longer maintaining this project sorry

**Comment by tim241** [comment]
Alright, omnisharp-roslyn has been updated to the latest git version today

Closing!

**Comment by Alias-777** [comment]
This question was asked almost two and a half years ago and today this is still an issue:

**Sublime**: 3.1.1 (BUILD: 3176)
**OmniSharp** v1.9.6

I would really love to use Sublime as my default code editor instead of VScode (where OmniSharp runs very decent and does not have this problem.), but this needs to be fixed.

`public int property{get; set;} = 0;`

Which outputs this after saving. (CTRL-s)

`Error : Unexpected symbol `='' in class, struct, or interface member declaration - (10, 40)`

So, how do I or we fix this?

**Comment by tim241** [comment]
Try the latest master, in a few days I'll have a new version ready :+1: @Alias-777

**Comment by Alias-777** [comment]
@tim241 Thanks for your reply. If it's just a view days, then I'll just wait for the new version and use VScode until then. If Omnisharp for Sublime works as nice as VScode's version then I will definitely make Sublime my new daily driver. But I really need decent C# support. (just as in VScode... I'm basically an Omnisharp addict now :).

**Comment by tim241** [comment]
@Alias-777 well I felt like making a release 3 hours ago, so omnisharp should update now with the updated stuff, make sure to check the requirements though!

**Comment by Alias-777** [comment]
@tim241 

Success! I've just installed the update (v1.9.7) and all seems to work as normal. Thanks for the great and fast response!

Also I did not have the VS2015 build tools (Installed from VS2015: "C:\Program Files (x86)\MSBuild\14.0\Bin") in my path. This was probably part of the problem. I **belief** I did try with VS2017 build tools but it failed.

Thanks! You've made me very happy!
